#Configuracion del servidor del microservicio
server:
  port: 8081

#Configuracion de datos de conexion de Base de Datos Mongo (Docker)
spring:
 data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27012/microsCondomino

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8099/eureka/
