#Configuracion del servidor del microservicio
server:
  port: 8082

#Configuracion de datos de conexion de Base de Datos Mongo (Docker)
spring:
 data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27011/microsEdificios
