#Configuracion del servidor del microservicio
server:
  port: 8082

#Configuracion de datos de conexion de Base de Datos Mongo (Docker)
spring:
 data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27011/microsEdificios

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8099/eureka/

resilience4j.circuitbreaker:
    configs:
        default:
            slidingWindowSize: 100
            permittedNumberOfCallsInHalfOpenState: 10
            waitDurationInOpenState: 10000
            failureRateThreshold: 60
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
        someShared:
            slidingWindowSize: 50
            permittedNumberOfCallsInHalfOpenState: 10
    instances:
        edificio:
            baseConfig: default
            waitDurationInOpenState: 5000
